DECLARE
IS_TABLE_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TABLE_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = 'USERS'
    AND OBJECT_TYPE = 'TABLE';

IF IS_TABLE_EXISTS = 1 THEN
EXECUTE IMMEDIATE q'[
    ALTER TABLE USERS
    ADD ACTIVE VARCHAR2(1) DEFAULT 1
    ]';

EXECUTE IMMEDIATE q'[
    ALTER TABLE USERS
    ADD CREATED_ON TIMESTAMP DEFAULT SYSTIMESTAMP
    ]';

EXECUTE IMMEDIATE q'[
    ALTER TABLE USERS
    ADD UPDATED_ON TIMESTAMP
    ]';
END IF;

END;
/

